-- This resource was generated by grzyClothTool :)
-- https://discord.gg/HCQutNhxWt

fx_version 'cerulean'
game 'gta5'
author 'grzyClothTool'

files {
  'mp_f_freemode_01_hair_cami.meta',
  'pedalternativevariations_hair_cami.meta'
}

data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_hair_cami.meta'
data_file 'ALTERNATE_VARIATIONS_FILE' 'pedalternativevariations_hair_cami.meta'
